TaskHelp/urls.py
from django.contrib import admin
from django.urls import include, path
from todo_api import urls as todo_urls

urlpatterns = [
    # path('', include('todo.urls')),
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
    # path('api-auth/', include('rest_framework.urls')),
    # path('todos/', include(todo_urls))
]

todo/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'todo'

urlpatterns = [
  # Ex: todo/
  path('', views.IndexView.as_view(), name='index'),

  # Ex: todo/2   --to view details
  path('<int:pk>/', views.DetailView.as_view(), name='details'),
  
  # Ex: todo/2/edit  --to edit the task
  path('<int:pk>/edit', views.edit, name='edit'),
  
  # Ex: todo/2/make_changes
  path('<int:pk>/make_changes', views.make_changes, name='make_changes'),
  
  # Ex: todo/add_task
  # path('add_task/', views.add_task, name='add_task'),

  # API
  path('api', views.TaskListApiView.as_view()),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime, pytz

class Task(models.Model):
  task_text = models.CharField(max_length=200)
  creation_date = models.DateTimeField('date created')
  due_date = models.DateTimeField('date[when] due')
  importance = models.CharField(max_length=20)
  user = models.ForeignKey(User, on_delete = models.CASCADE, blank = True, null = True)

  def __str__(self):
    return self.task_text

  def is_due(self):
    d = datetime.datetime.now()
    timezone = pytz.timezone("Africa/Lagos")
    d_aware = timezone.localize(d)
    return self.due_date <= d_aware

todo_api/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
  email = forms.EmailField()
  
  class Meta:
    model = User
    fields = ["username", "email", "password1", "password2"]

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm

# Create your views here.
def register(request):
  if request.method == "POST":
    form = RegisterForm(request.POST)
    if form.is_valid():
      print('Form is valid')
      form.save()
      return redirect('/todo')
  else:
    form = RegisterForm()
    
  return render(request, "register/register.html", {"form":form})

todo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions

from .models import Task
from .serializers import TaskSerializer

class IndexView(generic.ListView):
  template_name = 'todo/index.html'
  context_object_name = 'task_list'

  def get_queryset(self):
    return Task.objects.order_by('-due_date')
  

class DetailView(generic.DetailView):
  model = Task
  template_name = 'todo/details.html'


def edit(request, task_id):
  task = Task.objects.get(pk=task_id)
  return render(request, 'todo/edit.html', {'task': task})


def make_changes(request, task_id):
  task = get_object_or_404(Task, pk=task_id)

  task.task_text = request.POST["task_text"]
  task.due_date = request.POST["task_date"]
  task.importance = request.POST["importance"]
  task.save()

  return HttpResponseRedirect(reverse('todo:details', args=(task.id,))) 


class TaskListApiView(APIView):
  premission_classes = permissions.IsAuthenticated

  # List all tasks
  def get(self, request, *args, **kwargs):
    tasks = Task.objects.all()
    serializer = TaskSerializer(tasks, many=True)
    return Response(serializer.data, status=status.HTTP_200_OK)
  
  def post(self, request, *args, **kwargs):
    print(request)
    data = {
      'task_text': request.data.get('task_text'), 
      'creation_date': request.data.get('creation_date'), 
      'due_date': request.data.get('due_date'), 
      'importance': request.data.get('importance'), 
      'user': request.user.id 
    }

    serializer = TaskSerializer(data=data)

    if serializer.isValid():
      serializer.save()
      return Response(serializer.data, status = status.HTTP_201_CREATED)

    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

todo_api/views.py
from django.shortcuts import render

# Create your views here.

register/templates/register/register.html
{% extends 'todo/base.html' %}  

{% block title %} Todo | Create an account
{% endblock  %}

{% block content %}
  <h2> Create an account </h2>

  <form method="post">
    {% csrf_token %}
    {{form}}

    <button type="submit">Submit</button>
  </form>
{% endblock %}

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!--========================================================-->
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
    <!-- Title block -->
    <title>{% block title %}My amazing site{% endblock %}</title>
  </head>

  <body>
    <!-- Content block -->
    
    <div id="content">
      {% block content %}{% endblock %}
    </div>

  </body>
</html>

todo/templates/todo/details.html
{% extends 'todo/base.html' %}

{% block title%}
Todo | Details | Task {{task.id}}
{% endblock%}

{% block content %}
  
    {% if task %}
      <a href="{% url 'todo:index' %}">Home</a>

      <h2>{{task.task_text}}</h2>
      <a href="{% url 'todo:edit' task.id%} ">Edit</a>

      <div>
        <ul>
          <li>Date created: {{task.creation_date}}</li>
          <li>Date due: {{task.due_date}}</li>
          <li>Importance: {{task.importance}}</li>
          <li>
            {% if task.is_due %}
              <p style="color: red">Overdue</p>
            {% else %}
              <p style="color: green">Not yet due</p>
            {% endif %}
          </li>
        </ul>
      </div>

    {% endif %}
{% endblock%}

todo/templates/todo/edit.html
{% extends 'todo/base.html' %}

{% block title%}
  Todo | {{task.id}} | Edit 
{% endblock %}
  

{% block content%}
    <h2> {{task.task_text}}  </h2>

    <form action="{% url 'todo:make_changes' task.id%}" method="post">
      {% csrf_token %}

      <label for="{{task.id}}-text">Task text: </label>
      <input id="{{task.id}}-text" type="text" value="{{task.task_text}}" name="task_text" ><br>

      <label for="{{task.id}}-due-date">Due date: </label>
      <input id="{{task.id}}-due-date" type="date" name="task_date" ><br><!--Fix this line -->


      <label for="{{task.id}}-importance">Importance:</label>
      <select id="{{task.id}}-importance" name="importance" >
        <option value="high">High</option>
        <option value="medium">Medium</option>
        <option value="low">Low</option>
      </select><br>

      <input type="submit">
    </form>

{% endblock %}

todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block title %} Todo | All tasks
{% endblock %}
  
{% block content%}
  {% if task_list %}
    <h2>List of available tasks</h2>
    <ol>
      {% for task in task_list %}
        <li>
          <a href="{% url 'todo:details' task.id %}">
            {{task.task_text}}
          </a>
        </li>
      {% endfor %}
    </ol>
  {% endif %}   
{% endblock %}

todo/templates/todo/welcome.html
{% extends 'todo/base.html' %}

{% block title %}
Welcome to What's to do!!
{% endblock title %}

{% block content %}
  <h2>Welcome!!! glad  you're here </h2>

  <a href="/login"> Login </a>
  <p> New around here? Create an  <a href="/register"> account </a> </p>

  So, this is the welcome page


{% endblock content %}